version: '3.3'

services:
  dashboard-frontend-dev:
    container_name: dashboard-frontend-dev-for-aws
    build:
      context: ../..
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ../../:/root/dashboard
    environment:
      API_HOST: ${API_HOST:-http://localhost}
      API_PORT: 18080
    command:
      - /bin/bash
      - -c
      - "cd frontend && yarn install && yarn run start"
    depends_on:
      - dashboard-backend-dev
    ports:
      - "8080:8080"
  dashboard-backend-dev:
    container_name: dashboard-backend-dev-for-aws
    build:
      context: ../..
      dockerfile: ./drucker_dashboard/Dockerfile
    volumes:
      - ../../:/root/dashboard
      - ~/.aws:/root/.aws
    environment:
      FLASK_DEBUG: "True"
      PYTHONIOENCODING: "utf-8"
    command:
      - /bin/bash
      - -c
      - "pip install -r requirements.txt && pip install -e . && cd drucker_dashboard && (rekcurdui --settings settings.yml db init || true) && (rekcurdui --settings settings.yml db migrate || true) && rekcurdui --settings settings.yml server"
    ports:
      - "18080:18080"
