apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rekcurd-test-app
    sel: rekcurd-test-app-development-20180628151929
  name: rekcurd-test-app-development-20180628151929-deployment
  namespace: development
spec:
  minReadySeconds: 300
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      sel: rekcurd-test-app-development-20180628151929
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rekcurd-test-app
        sel: rekcurd-test-app-development-20180628151929
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - rekcurd-test-app-development-20180628151929
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - command:
        - sh
        - /usr/local/src/entrypoint.sh
        env:
        - name: REKCURD_SERVICE_UPDATE_FLAG
          value: Edit here to run rolling update
        - name: REKCURD_SERVICE_ENV
          value: development
        - name: REKCURD_SERVICE_GIT_URL
          value: https://github.com/rekcurd/rekcurd-example.git
        - name: REKCURD_SERVICE_GIT_BRANCH
          value: v0.5.0a0
        - name: REKCURD_SERVICE_BOOT_SHELL
          value: start.sh
        - name: REKCURD_SERVICE_MODEL_DIR
          value: /mnt/rekcurd-model
        - name: REKCURD_SERVICE_NAME
          value: rekcurd-test-app-development-20180628151929
        image: rekcurd/rekcurd:python-latest
        imagePullPolicy: Always
        name: rekcurd-test-app-development-20180628151929
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: 1
            memory: 256Mi
          requests:
            cpu: 0.5
            memory: 128Mi
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /mnt/rekcurd-model
          name: host-volume
      nodeSelector:
        host: development
      volumes:
      - hostPath:
          path: /mnt/rekcurd-model
        name: host-volume
