apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    rekcurd-worker: "true"
    id: id-test20190307093000
    name: app-test20190307093000
    sel: test20190307093000
  name: deploy-test20190307093000
  namespace: development
spec:
  minReadySeconds: 300
  progressDeadlineSeconds: 3000
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      sel: test20190307093000
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        rekcurd-worker: "true"
        id: id-test20190307093000
        name: app-test20190307093000
        sel: test20190307093000
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: id
                  operator: In
                  values:
                  - test20190307093000
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - env:
        - name: REKCURD_SERVICE_UPDATE_FLAG
          value: Edit here to run rolling update
        - name: REKCURD_KUBERNETES_MODE
          value: "true"
        - name: REKCURD_DEBUG_MODE
          value: "true"
        - name: REKCURD_APPLICATION_NAME
          value: app-test20190307093000
        - name: REKCURD_SERVICE_INSECURE_HOST
          value: "[::]"
        - name: REKCURD_SERVICE_INSECURE_PORT
          value: "5000"
        - name: REKCURD_SERVICE_ID
          value: test20190307093000
        - name: REKCURD_SERVICE_LEVEL
          value: development
        - name: REKCURD_GRPC_PROTO_VERSION
          value: v2
        - name: REKCURD_MODEL_MODE
          value: local
        - name: REKCURD_MODEL_FILE_PATH
          value: model/default.model
        - name: REKCURD_SERVICE_GIT_URL
          value: https://github.com/rekcurd/rekcurd-example.git
        - name: REKCURD_SERVICE_GIT_BRANCH
          value: master
        - name: REKCURD_SERVICE_BOOT_SHELL
          value: start.sh
        image: rekcurd/rekcurd:python-latest
        imagePullPolicy: Always
        name: test20190307093000
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: 1
            memory: 512Mi
          requests:
            cpu: 0.5
            memory: 512Mi
        securityContext:
          privileged: true
      nodeSelector:
        host: development
